
* DHBB

** Split meta from text

Para separar arquivos já limpos em um diretório:

#+BEGIN_SRC sh
for f in $(egrep '^cargos:' *.text | awk -F ':' '{ print $1 }'); do cp $f test/; done
#+END_SRC

Para separar metadados dos textos:

#+BEGIN_SRC sh
  for f in *.text; do
      awk 'BEGIN { text=0; } text>1 {print} /^---$/ { text = text + 1; }' $f > $(basename $f .text).txt ;
  done
#+END_SRC

** Files

This dictionary has seven directories: 

- html :: Holds the original html files for each dictionary entry.

- md :: Holds the markdown files from of each html file entry.

- meta :: Holds the processed meta data information compiled in the
     first paragraph of each dictionary entry.  Each meta file holds
     the following fields: a) title b) each position is comprised of 5
     different fields (represented by a list, each position entry
     means an item of list for each field): cargoss (position),
     cargos\_esp (detail of the position), datas\_ini (initial date),
     datas_fim (end date), estados (state where the position was
     taken).  c) autor (author of the entry)

- ref :: Holds the reference text in each dictionary entry.

- txt :: Holds the text body in each dictionary entry.

- json :: Holds the son files containing the meta data, text and ref
     information structured in a json file.

- meta_flat :: Holds the meta data information from the old database
     system. Each meta file holds the following fields: a) layout
     (always ‘verbete’) b) title (list of possible titles) c)
     published (boolean) d) edition e) updated (date of last update)
     f) type (B for biographic or T for thematic) g) subtype (when
     biographic, its subtype) h) each position is comprised of 5
     different fields (represented by a list, each position entry
     means an item of list for each field): codigos (id in DB), starts
     (starting date), ends (ending date), cities (city where the
     position was taken), ufs (state where the position was taken),
     countries (country where the position was taken), institutions
     (institution of the position), cargoss (name of the position),
     cargo\_abbrevs (abbreviation of the position), cargo\_types (type
     of position), funcoes (function related to the position),
     governments (governments in which the position was taken),
     government\_inis (starting date of the government),
     government_ends (ending date of the government)

** Links

- http://pyyaml.org/wiki/PyYAMLDocumentation
- http://www.w3.org/TR/rdf-sparql-query/
