#+Title: Dicionário Histórico-Biográfico Brasileiro - DHBB

(English Version at [[README-EN.org]])

O projeto do DHBB começou a ser desenvolvido na FGV CPDOC em 1974,
produzindo seu primeiro resultado dez anos depois. Era um tempo em que
o acesso à internet ainda não era generalizado. Pesquisar sobre temas
da história contemporânea do Brasil, além de exigir o domínio da
bibliografia pertinente, significava sair em campo para localizar
arquivos, consultar coleções de jornais, obter anuários e anais
oficiais, entrevistar pessoas.

Publicar significava editar volumes em papel. Exatamente o que foi
feito, com a primeira edição do DHBB saindo em 1984, com seus quatro
volumes e 4.493 verbetes. Ao consolidar informações até então esparsas
com o devido registro das fontes consultadas, a enciclopédia sobre a
elite política brasileira tornou-se pioneira, consolidando-se como
obra de referência para novas pesquisas. Lançada em 2001, a segunda
edição do DHBB atualizou os verbetes existentes e incluiu novos,
atingindo um total de 6.620 entradas. Uma novidade chamou a atenção na
época: a dupla publicação, em papel e em CD-ROM.

Iniciado novo processo de atualização, num mundo em que a revolução da
informática era fato consumado e novos caminhos se abriam à pesquisa
histórica, realizaram-se concomitantemente estudos visando à
democratização do acesso ao DHBB. Em 2010, nova versão do Dicionário,
pôde ser assim oferecida na web, com acesso gratuito e aberto a
todos. São 7.553 verbetes, sendo 6.584 de natureza biográfica e 969
verbetes temáticos, relativos a instituições, eventos e conceitos de
interesse para a história do Brasil pós-1930.

Todos os verbetes agora podem ser consultados e lidos na íntegra a
partir da base de dados integrada do Acervo do CPDOC. Para acessar
basta se cadastrar gratuitamente na própria página de busca

[[http://www.fgv.br/cpdoc/busca/]]

Este repositório contém os arquivos dos verbetes em formato texto com
respectivos metadados. Estes arquivos contém os mesmos conteúdos que
podem ser consultados no link acima. 

O principal objetivo deste repositório é dar acesso integral ao DHBB à
pesquisadores interessados no processamento automático dos textos,
inclusive para efeito de mineracao de dados.

* Arquivos

- text :: neste diretório encontram-se os verbetes do DHBB,
  atualizados constantemente pela equipe da FGV CPDOC.

- ref :: em versões anteriores do DHBB, os verbetes eram finalizados
  com referências as fontes utilizadas pelos editores. Infelizmente,
  ao longo dos anos, a forma de referência às fontes não foi
  padronizada e por isso separamos neste diretório as referências
  antes incluídas no final de cada verbete.

Cada arquivo no diretório =text= contém metadados e o texto dos
verbetes. Os arquivos são codificados em UTF-8. No cabeçalho, iniciado
e terminado com linhas contendo três hífens =---=, temos os metadados
do verbete no formato [[https://yaml.org][YAML]]. O texto dos verbetes é codificado em
[[https://daringfireball.net/projects/markdown/][Markdown]] mas no momento, apenas separadores de seções são usados.
       
* License

Veja o arquivo LICENSE

* Como Contribuir

Convidamos qualquer usuário deste repositório ou usuário do site
[[http://www.fgv.br/cpdoc/busca/]] que encontre imprecisões nos textos do DHBB,
a criar um ISSUE neste repositório indicando o problema encontrado. 

A criação de novos verbetes ou significativas mudanças em seus
conteúdos são, no entanto, objetivo de avaliação e aprovação pela
equipe do DHBB, que detem a prerrogativa de gestão editorial do corpus.

* Versões

O DHBB adota o [[https://semver.org/lang/pt-BR/][versionamento semântico]]. A primeira release usando este
versionamento é a 1.0.0. O critério para novas releases será:

- MAJOR :: quando mudanças na organização ou formato dos
  arquivos. Mudanças nos metadados utilizados. Mudanças de muitos
  arquivos por alguma tarefa sistemática da equipe do DHBB.

- MINOR :: mudanças pontuais em um número limitado de verbetes, adição
  ou remoção de alguns poucos verbetes.

- PATCH :: qualquer correção nos textos não relacionada à mudança de
  conteúdo. Correção de [[https://en.wikipedia.org/wiki/Typographical_error][typo]] ou erros de codificação etc.
